server:
  port: 8762
spring:
  application:
    name: nativeconfigserver
  #`profiles.active`：配置文件的获取方式
  profiles:
    active: native
  #`cloud.config.server.native.search-locations`：本地配置文件存放的路径
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared